name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  Clone-fuel: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone fuel repo
        uses: appleboy/ssh-action@master
        with:
          script: |
            rm -rf ~/fuel
            git clone -b main git@github.com:brockai/fuel.git
            rm /var/www/fuel -r || true
            cp ~/fuel -r /var/www/fuel

  Deploy-Node-Server:
    runs-on: ubuntu-latest
    needs: Clone-fuel
    steps:
      - name: Deploy node server
        uses: appleboy/ssh-action@master
        with:
          script: |
            # remove existing node server, copy over node server
            rm /var/www/contact-node -r || true
            mkdir /var/www/contact-node || true
            cp ~/fuel/server/. -r /var/www/contact-node
            cp ~/.env.contact-node /var/www/contact-node/.env
            cd /var/www/contact-node
            npm install
            pm2 delete "contact"
            pm2 start contact.js