name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  Clone-bmel: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone bmel repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf ~/bmel
            eval `ssh-agent -s`
            ssh-addm~/.ssh/git_id_rsa
            git clone -b main git@github.com:brockai/bmel.git

  Deploy-Node-Server:
    runs-on: ubuntu-latest
    needs: Clone-bmel
    steps:
      - name: Deploy node server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # remove existing node server, copy over node server
            rm /var/www/bmel-node -r || true
            mkdir /var/www/bmel-node || true
            cp ~/bmel/server/. -r /var/www/bmel-node
            cp ~/bmel/server/geotab -r /var/www/bmel-node
            cp ~/bmel/server/opensearch -r /var/www/bmel-node
            cp ~/.env.bmel-node /var/www/bmel-node/.env
            cd /var/www/bmel-node
            npm install
            pm2 delete "geotab"
            pm2 delete "opensearch"
            pm2 start geotab/geotab.js
            pm2 start opensearch/opensearch.js
            
  Deploy-Bmel-Client:
    runs-on: ubuntu-latest
    needs: Clone-bmel
    steps:
      - name: Deploy client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            use 18.17.0

            cd ~/bmel/client/
            rm /var/www/bmel -r || true
            cp ~/bmel/client -r /var/www/bmel
            cp ~/.env.local /var/www/bmel/.env.local
            cd /var/www/bmel
            npm install
            npm run build
            if [ $? -eq 0 ]; then
              pm2 delete "bmel-client"
              pm2 start npm --name "bmel-client" -- start
            else
              echo "Build failed, deployment aborted."
              exit 1
            fi
