name: Deploy Wiki to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the wiki repository
        run: |
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.DROPLET_IP}}
            username: ${{ secrets.DROPLET_USERNAME }}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            script: |
              git clone https://github.com/brockai/fuel/wiki wiki
              # git clone https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.wiki.git wiki
            
      - name: Deploy wiki to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r wiki/* docs
          cp -r maintenance/* docs
          git config --global user.name 'brock'
          git config --global user.email 'bclayton403@gmail.com'
          git add docs
          git commit -m 'Deploy wiki to GitHub Pages'
          git push
